### ISSUE TITLE
Confirmation mail never received

### ISSUE THREAD

**Issue by alaakaazaam** [smislav/iota-poker-issues#3] opened 2022-01-12 16:28 UTC
All is in the title.
I created my account, but still waiting for the confirmation.
When i come back to the page and click on the upper-right 'login' link : nothing more happens...

**Comment by smislav** [comment] 2022-01-12 17:13
Please check your junk in the email.

If there is still no confirmation email, please provide me an email you used for registration.

**Comment by alaakaazaam** [comment] 2022-01-13 16:29
still no mail, pacabreizh@gmail.com

**Comment by smislav** [comment] 2022-01-17 23:41
It was caused by server timeout, I have made a few updates.
1. If you try to log in with an unverified account you will receive a new verification email
2. Account is now set up after login, this makes server timeout less possible at registration time

I'll consider this issue solved for now and close it.

Thanks

**Closed by smislav** 2022-01-17 23:41 UTC
